/**
 * Created by coud on 8/1/16.
 */
 export default {
   FETCH: 'FETCH ALL ASSIGNEMNTS WITH BASIC INFORMATION V02',
   FETCH_CURRENT: 'FETCH CURRENT ASSIGNMENT V02',
   DELETE: 'DELETE ASSIGNMENT V2',
   DEMAND_VALIDATION: 'DEMAND ASSIGNMENT VALIDATION V2',
   RETIRE: 'RETIRE ASSIGNMENT VALIDATION V2',
   PUBLISH: 'PUBLISH ASSIGNMENT VALIDATION V2',
 };
