export default {
  FETCH_LATEST: 'FRONT PRODUCTS LATEST',
  FETCH_ONE: 'FETCH CURRENT SELECTED PRODUCT WITH BASIC INFORMATION V02',
  FETCH_ALL: 'FETCH ALL PRODUCTS WITH BASIC INFORMATION V02',
  REQUEST_PRODUCTS: 'REQUEST_PRODUCTS V02',
  RECEIVE_PRODUCTS: 'RECEIVE_PRODUCTS V02',
  REQUEST_PRODUCT: 'REQUEST_PRODUCT V02',
  RECEIVE_PRODUCT: 'RECEIVE_PRODUCT V02',
  FETCH_OFFERS_OF_PRODUCT: 'FETCH OFFERS IN PROABONO FOR AN SPECIFIC PRODUCT/PROABONO-FEATURE V02',
  UPDATE: 'UPDATE ONE PRODUCT',
};
