export default {
  FETCH_LATEST: 'FRONT PRODUCTS LATEST',
  FETCH_ONE: 'FETCH CURRENT SELECTED PRODUCT WITH BASIC INFORMATION V02',
  FETCH_ALL: 'FETCH ALL PRODUCTS WITH BASIC INFORMATION V02',
  FETCH_OFFERS_OF_PRODUCT: 'FETCH OFFERS IN PROABONO FOR AN SPECIFIC PRODUCT/PROABONO-FEATURE V02',
  UPDATE: 'UPDATE ONE PRODUCT',
};
