export default {
  FETCH: 'FRONT FETCH ALL DOMAINS V02',
  FETCH_ONE: 'FETCH CURRENT SELECTED DOMAIN WITH BASIC INFORMATION V02',
  FETCH_PRODUCTS: 'FETCH ALL PRODUCTS FOR CURRENT SELECTED DOMAIN V02',
  FETCH_BUNDLES: 'FETCH ALL BUNDLES FOR CURRENT SELECTED DOMAIN V02',
};
