export default {
  FETCH: 'FRONT FETCH ALL USER CORNERS V02',
  FETCH_ONE: 'FETCH CURRENT SELECTED USER CORNER WITH BASIC INFORMATION V02',
  FETCH_PRODUCTS: 'FETCH ALL PRODUCTS FOR CURRENT SELECTED USER CORNER V02',
  FETCH_BUNDLES: 'FETCH ALL BUNDLES FOR CURRENT SELECTED USER CORNER V02',
};
