/**
 * Created by coud on 8/1/16.
 */
 export default {
   SET_SITE: 'SET SEO INFORMATION SITE SETTINGS V02',
   SET_PAGE: 'SET SEO INFORMATION FOR SPECIFIC V02',
   SET_URL: 'SET LOCAL URL V02',
   SET_FB_ID: 'SET FACEBOOK META INFORMATION ID V02',
 };
